# .cpanel.yml
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/lajix/public_html/mastergolf.lajix.com/django/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R apis $DEPLOYPATH
    - /bin/cp -R mgc $DEPLOYPATH
    - /bin/cp -R media $DEPLOYPATH
    - /bin/cp manage.py $DEPLOYPATH
    - /bin/cp requirements.txt $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH

