# Generated by Django 5.0.12 on 2025-06-12 08:12

import django.core.validators
import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmenitiesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amenityName', models.CharField(blank=True, max_length=200, null=True)),
                ('amenityIcon', models.TextField(blank=True, null=True)),
                ('amenityTooltip', models.CharField(blank=True, max_length=500, null=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogDate', models.DateField()),
                ('blogTitle', models.CharField(max_length=255)),
                ('blogHighlight', models.TextField(blank=True, null=True)),
                ('blogDescription', tinymce.models.HTMLField()),
                ('blogImage', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConceptModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conceptHighlight', models.CharField(max_length=1500)),
                ('conceptCount', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(8)])),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Concept',
                'verbose_name_plural': 'Concepts',
            },
        ),
        migrations.CreateModel(
            name='ContactEnquiryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactEnquiryDate', models.DateField(auto_now_add=True)),
                ('contactEnquiryFirstName', models.CharField(max_length=255)),
                ('contactEnquiryLastName', models.CharField(max_length=255)),
                ('contactEnquiryPhoneNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('contactEnquiryEmail', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('contactEnquiryMessage', models.TextField()),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CountryModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('countryName', models.CharField(blank=True, max_length=255, null=True)),
                ('countryCode', models.CharField(blank=True, max_length=55, null=True)),
                ('dailCode', models.CharField(blank=True, max_length=10, null=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenderModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('genderName', models.CharField(blank=True, max_length=255, null=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethodModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('methodName', models.CharField(max_length=50, null=True, unique=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentStatusModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('statusName', models.CharField(max_length=50, null=True, unique=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanCycleModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('planCycleName', models.CharField(blank=True, max_length=200, null=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanDurationModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('planDurationName', models.CharField(blank=True, max_length=200, null=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanTypeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('planTypeName', models.CharField(blank=True, max_length=200, null=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTypeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userTypeName', models.CharField(blank=True, max_length=200, null=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConceptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('paragraph', models.TextField(max_length=1000)),
                ('order', models.IntegerField(default=0)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='apis.conceptmodel')),
            ],
            options={
                'verbose_name': 'Concept Item',
                'verbose_name_plural': 'Concept Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(blank=True, max_length=255, null=True)),
                ('courseAddress', models.TextField(blank=True, null=True)),
                ('courseOpenFrom', models.CharField(blank=True, max_length=255, null=True)),
                ('coursePhoneNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('courseAlternatePhoneNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('courseWebsite', models.URLField(blank=True, max_length=255, null=True)),
                ('courseDescription', models.TextField(blank=True, null=True)),
                ('courseLocation', models.CharField(blank=True, help_text='GPS coordinates or detailed location for directions', max_length=500, null=True)),
                ('courseImage', models.ImageField(blank=True, null=True, upload_to='course_images/')),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('courseAmenities', models.ManyToManyField(blank=True, related_name='courses', to='apis.amenitiesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='PlanModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('planName', models.CharField(blank=True, max_length=255, null=True)),
                ('planDescription', models.CharField(blank=True, max_length=255, null=True)),
                ('planPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('planCycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planCycle', to='apis.plancyclemodel')),
                ('planDuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planDuration', to='apis.plandurationmodel')),
                ('planType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planType', to='apis.plantypemodel')),
            ],
        ),
        migrations.CreateModel(
            name='MemberModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(blank=True, max_length=150, null=True)),
                ('lastName', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('encrypted_password', models.TextField(blank=True, null=True)),
                ('hashed_password', models.TextField(blank=True, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('alternatePhoneNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('dateOfBirth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('membershipStartDate', models.DateField(blank=True, null=True)),
                ('membershipEndDate', models.DateField(blank=True, null=True)),
                ('emergencyContactName', models.CharField(blank=True, max_length=200, null=True)),
                ('emergencyContactPhone', models.CharField(blank=True, max_length=20, null=True)),
                ('emergencyContactRelation', models.CharField(blank=True, max_length=100, null=True)),
                ('referredBy', models.CharField(blank=True, max_length=200, null=True)),
                ('profilePhoto', models.ImageField(blank=True, null=True, upload_to='member_photos/')),
                ('idProof', models.FileField(blank=True, null=True, upload_to='member_id_proofs/')),
                ('handicap', models.BooleanField(default=False)),
                ('golfClubId', models.CharField(blank=True, max_length=100, null=True)),
                ('qr_token', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberGender', to='apis.gendermodel')),
                ('nationality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberNationality', to='apis.countrymodel')),
                ('paymentMethod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberPaymentMethod', to='apis.paymentmethodmodel')),
                ('paymentStatus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberPaymentStatus', to='apis.paymentstatusmodel')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberPlan', to='apis.planmodel')),
            ],
        ),
        migrations.CreateModel(
            name='MemberEnquiryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberEnquiryDate', models.DateField(auto_now_add=True)),
                ('memberEnquiryFirstName', models.CharField(blank=True, max_length=150, null=True)),
                ('memberEnquiryLastName', models.CharField(blank=True, max_length=150, null=True)),
                ('memberEnquiryEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('memberEnquiryPhoneNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('memberEnquiryMessage', models.TextField(blank=True, null=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('memberEnquiryPlan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberEnquiryPlan', to='apis.planmodel')),
            ],
            options={
                'verbose_name': 'Member Enquiry',
                'verbose_name_plural': 'Member Enquiries',
                'ordering': ['-createdAt'],
            },
        ),
    ]
