# Generated by Django 5.0.7 on 2025-01-29 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanCycleModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('planCycleName', models.CharField(blank=True, max_length=200, null=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanDurationModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('planDurationName', models.CharField(blank=True, max_length=200, null=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanTypeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('planTypeName', models.CharField(blank=True, max_length=200, null=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTypeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userTypeName', models.CharField(blank=True, max_length=200, null=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('planName', models.CharField(blank=True, max_length=255, null=True)),
                ('planDescription', models.CharField(blank=True, max_length=255, null=True)),
                ('planPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('planCycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planCycle', to='apis.plancyclemodel')),
                ('planDuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planDuration', to='apis.plandurationmodel')),
                ('planType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planType', to='apis.plantypemodel')),
            ],
        ),
    ]
