# Generated by Django 5.0.12 on 2025-06-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membermodel',
            options={'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
        migrations.AddField(
            model_name='membermodel',
            name='enquiryId',
            field=models.CharField(blank=True, help_text='ID of the original enquiry if member was created from enquiry', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='membermodel',
            name='enquiryMessage',
            field=models.TextField(blank=True, help_text='Original enquiry message', null=True),
        ),
        migrations.AlterModelTable(
            name='membermodel',
            table='member',
        ),
    ]
