# Generated by Django 5.0.7 on 2025-01-29 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('countryName', models.CharField(blank=True, max_length=255, null=True)),
                ('countryCode', models.CharField(blank=True, max_length=55, null=True)),
                ('dailCode', models.CharField(blank=True, max_length=10, null=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenderModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('genderName', models.CharField(blank=True, max_length=255, null=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethodModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('methodName', models.CharField(max_length=50, null=True, unique=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentStatusModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('statusName', models.CharField(max_length=50, null=True, unique=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemberModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(blank=True, max_length=150, null=True)),
                ('lastName', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('alternatePhoneNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('dateOfBirth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('membershipStartDate', models.DateField(blank=True, null=True)),
                ('membershipEndDate', models.DateField(blank=True, null=True)),
                ('emergencyContactName', models.CharField(blank=True, max_length=200, null=True)),
                ('emergencyContactPhone', models.CharField(blank=True, max_length=20, null=True)),
                ('emergencyContactRelation', models.CharField(blank=True, max_length=100, null=True)),
                ('referredBy', models.CharField(blank=True, max_length=200, null=True)),
                ('profilePhoto', models.ImageField(blank=True, null=True, upload_to='member_photos/')),
                ('idProof', models.FileField(blank=True, null=True, upload_to='member_id_proofs/')),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberGender', to='apis.gendermodel')),
                ('nationality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberNationality', to='apis.countrymodel')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberPlan', to='apis.planmodel')),
                ('paymentMethod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberPaymentMethod', to='apis.paymentmethodmodel')),
                ('paymentStatus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberPaymentStatus', to='apis.paymentstatusmodel')),
            ],
        ),
    ]
