# Generated by Django 5.0.12 on 2025-06-04 11:38

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptitem',
            name='paragraph',
            field=tinymce.models.HTMLField(),
        ),
    ]
