# Generated by Django 5.0.7 on 2025-01-30 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_countrymodel_gendermodel_paymentmethodmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membermodel',
            name='golfClubId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='membermodel',
            name='handicap',
            field=models.BooleanField(default=False),
        ),
    ]
