# Generated by Django 5.0.12 on 2025-06-12 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_membermodel_options_membermodel_enquiryid_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='membermodel',
            table=None,
        ),
    ]
