# Generated by Django 5.0.12 on 2025-06-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_conceptitem_paragraph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptitem',
            name='paragraph',
            field=models.TextField(max_length=1000),
        ),
    ]
