# Generated by Django 5.0.12 on 2025-06-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_alter_conceptitem_paragraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='membermodel',
            name='qr_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
