# Generated by Django 5.0.7 on 2025-01-31 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_membermodel_golfclubid_membermodel_handicap'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmenitiesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amenityName', models.CharField(blank=True, max_length=200, null=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberGender', to='apis.gendermodel'),
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberNationality', to='apis.countrymodel'),
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='paymentMethod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberPaymentMethod', to='apis.paymentmethodmodel'),
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='paymentStatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberPaymentStatus', to='apis.paymentstatusmodel'),
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberPlan', to='apis.planmodel'),
        ),
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(blank=True, max_length=255, null=True)),
                ('courseNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('streetName', models.CharField(blank=True, max_length=255, null=True)),
                ('locality', models.CharField(blank=True, max_length=255, null=True)),
                ('town', models.CharField(blank=True, max_length=255, null=True)),
                ('postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('golfDescription', models.TextField(blank=True, null=True)),
                ('golfLocation', models.CharField(blank=True, max_length=255, null=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('amenities', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='apis.amenitiesmodel')),
            ],
        ),
    ]
