# Generated by Django 5.0.12 on 2025-06-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_membermodel_qr_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenitiesmodel',
            name='amenityIcon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='amenitiesmodel',
            name='amenityTooltip',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='timing',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='courses', to='apis.amenitiesmodel'),
        ),
    ]
