# Generated by Django 5.0.12 on 2025-07-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_contactenquirymodel_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membermodel',
            name='reset_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='membermodel',
            name='reset_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
