# Generated by Django 5.0.7 on 2025-01-31 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_amenitiesmodel_alter_membermodel_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodel',
            name='amenities',
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='amenities', to='apis.amenitiesmodel'),
        ),
    ]
