# Generated by Django 5.0.7 on 2025-01-31 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_remove_coursemodel_amenities_coursemodel_amenities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodel',
            name='amenities',
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='amenities',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='apis.amenitiesmodel'),
        ),
    ]
