# Generated by Django 5.0.12 on 2025-07-30 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_membermodel_reset_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('holeNumber', models.IntegerField(help_text='Number of holes for this tee (e.g., 9 or 18)')),
                ('label', models.CharField(blank=True, help_text="Optional name like 'Morning 9 Holes'", max_length=100, null=True)),
                ('pricePerPerson', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tees', to='apis.coursemodel')),
            ],
        ),
        migrations.CreateModel(
            name='BookingModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bookingDate', models.DateField()),
                ('bookingTime', models.TimeField()),
                ('participants', models.PositiveIntegerField(default=1)),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='apis.coursemodel')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='apis.membermodel')),
                ('tee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='apis.teemodel')),
            ],
        ),
    ]
