# Generated by Django 5.0.12 on 2025-06-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_amenitiesmodel_amenityicon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenitiesmodel',
            name='amenityIcon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
