# Generated by Django 5.0.12 on 2025-07-31 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_teemodel_bookingmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teemodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='teemodel',
            name='label',
        ),
    ]
