# Generated by Django 5.0.12 on 2025-06-10 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_alter_amenitiesmodel_amenityicon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodel',
            name='timing',
        ),
    ]
