# Generated by Django 5.0.7 on 2025-01-31 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_blogmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='blogImage',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
    ]
