# Generated by Django 5.0.12 on 2025-06-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_remove_coursemodel_timing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursemodel',
            old_name='golfDescription',
            new_name='courseAddress',
        ),
        migrations.RenameField(
            model_name='coursemodel',
            old_name='phoneNumber',
            new_name='courseAlternatePhoneNumber',
        ),
        migrations.RenameField(
            model_name='coursemodel',
            old_name='amenities',
            new_name='courseAmenities',
        ),
        migrations.RenameField(
            model_name='coursemodel',
            old_name='golfHighlight',
            new_name='courseDescription',
        ),
        migrations.RenameField(
            model_name='coursemodel',
            old_name='golfLocation',
            new_name='courseOpenFrom',
        ),
        migrations.RenameField(
            model_name='coursemodel',
            old_name='postcode',
            new_name='coursePhoneNumber',
        ),
        migrations.RenameField(
            model_name='coursemodel',
            old_name='website',
            new_name='courseWebsite',
        ),
        migrations.RemoveField(
            model_name='coursemodel',
            name='country',
        ),
        migrations.RemoveField(
            model_name='coursemodel',
            name='courseNumber',
        ),
        migrations.RemoveField(
            model_name='coursemodel',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='coursemodel',
            name='streetName',
        ),
        migrations.RemoveField(
            model_name='coursemodel',
            name='town',
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='courseLocation',
            field=models.CharField(blank=True, help_text='GPS coordinates or detailed location for directions', max_length=500, null=True),
        ),
    ]
