# Generated by Django 5.0.12 on 2025-07-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_remove_teemodel_description_remove_teemodel_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teemodel',
            name='holeNumber',
            field=models.IntegerField(help_text='Number of holes for this tee (any positive integer)'),
        ),
    ]
