# Generated by Django 5.0.7 on 2025-02-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_blogmodel_blogimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='membermodel',
            name='encrypted_password',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membermodel',
            name='hashed_password',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membermodel',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
