# Generated by Django 5.0.12 on 2025-08-01 10:58

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_alter_teemodel_holenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aboutHeading', models.CharField(blank=True, help_text='About section heading', max_length=255, null=True)),
                ('aboutDescription', tinymce.models.HTMLField(blank=True, help_text='About section description with rich text', null=True)),
                ('partnerGolfClubs', models.IntegerField(default=0, help_text='Number of partner golf clubs')),
                ('successfulYears', models.IntegerField(default=0, help_text='Number of successful years')),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Sections',
            },
        ),
    ]
