# Generated by Django 5.0.7 on 2025-02-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_membermodel_encrypted_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodel',
            name='amenities',
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='amenities',
            field=models.ManyToManyField(blank=True, null=True, related_name='amenities', to='apis.amenitiesmodel'),
        ),
    ]
