# Generated by Django 5.0.7 on 2025-08-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_blogmodel_blogquote_blogmodel_blogquotecreator'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Event title', max_length=255)),
                ('date', models.CharField(help_text="Display date (e.g., '22 August')", max_length=50)),
                ('location', models.CharField(help_text='Event location', max_length=255)),
                ('main_image', models.ImageField(help_text='Main event image', upload_to='events/main/')),
                ('image_1', models.ImageField(blank=True, help_text='Additional image 1', null=True, upload_to='events/gallery/')),
                ('image_2', models.ImageField(blank=True, help_text='Additional image 2', null=True, upload_to='events/gallery/')),
                ('image_3', models.ImageField(blank=True, help_text='Additional image 3', null=True, upload_to='events/gallery/')),
                ('image_4', models.ImageField(blank=True, help_text='Additional image 4', null=True, upload_to='events/gallery/')),
                ('description', models.TextField(help_text='Main event description')),
                ('additional_info', models.TextField(blank=True, help_text='Additional information about the event', null=True)),
                ('activities_description', models.TextField(help_text='Description of activities and features')),
                ('additional_activities', models.TextField(blank=True, help_text='Additional activities information', null=True)),
                ('organizer', models.CharField(help_text='Event organizer name', max_length=255)),
                ('start_date', models.DateField(help_text='Event start date')),
                ('end_date', models.DateField(help_text='Event end date')),
                ('time', models.CharField(help_text="Event time (e.g., '12:00 PM')", max_length=50)),
                ('cost', models.CharField(help_text="Event cost (e.g., '$60')", max_length=50)),
                ('venue', models.CharField(help_text='Venue name', max_length=255)),
                ('address', models.TextField(help_text='Venue address')),
                ('email', models.EmailField(help_text='Contact email', max_length=254)),
                ('phone', models.CharField(help_text='Contact phone number', max_length=50)),
                ('website', models.URLField(blank=True, help_text='Venue website', null=True)),
                ('event_options', models.JSONField(blank=True, default=list, help_text='Event options for contact form dropdown as JSON array')),
                ('is_active', models.BooleanField(default=True, help_text='Is event active/visible')),
                ('is_featured', models.BooleanField(default=False, help_text='Is event featured')),
                ('meta_description', models.TextField(blank=True, help_text='SEO meta description', max_length=160, null=True)),
                ('slug', models.SlugField(blank=True, help_text='URL slug for the event', unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('hideStatus', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-start_date', '-createdAt'],
            },
        ),
    ]
