# Generated by Django 5.0.7 on 2025-02-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_remove_coursemodel_amenities_coursemodel_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='amenities', to='apis.amenitiesmodel'),
        ),
    ]
