# Generated by Django 5.0.7 on 2025-08-02 06:10

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0011_eventmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventmodel',
            options={'ordering': ['-EventEndDate', '-createdAt'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.RenameField(
            model_name='eventmodel',
            old_name='date',
            new_name='EventDate',
        ),
        migrations.RenameField(
            model_name='eventmodel',
            old_name='organizer',
            new_name='EventDetailOrganizer',
        ),
        migrations.RenameField(
            model_name='eventmodel',
            old_name='email',
            new_name='EventEmail',
        ),
        migrations.RenameField(
            model_name='eventmodel',
            old_name='end_date',
            new_name='EventEndDate',
        ),
        migrations.RenameField(
            model_name='eventmodel',
            old_name='main_image',
            new_name='EventImage',
        ),
        migrations.RenameField(
            model_name='eventmodel',
            old_name='phone',
            new_name='EventPhone',
        ),
        migrations.RenameField(
            model_name='eventmodel',
            old_name='time',
            new_name='EventTime',
        ),
        migrations.RenameField(
            model_name='eventmodel',
            old_name='title',
            new_name='EventTitle',
        ),
        migrations.RemoveField(
            model_name='eventmodel',
            name='activities_description',
        ),
        migrations.RemoveField(
            model_name='eventmodel',
            name='additional_activities',
        ),
        migrations.RemoveField(
            model_name='eventmodel',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='eventmodel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='eventmodel',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='eventmodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='eventmodel',
            name='event_options',
        ),
        migrations.RemoveField(
            model_name='eventmodel',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='eventmodel',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='eventmodel',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='eventmodel',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='eventmodel',
            name='location',
        ),
        migrations.RemoveField(
            model_name='eventmodel',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='eventmodel',
            name='venue',
        ),
        migrations.RemoveField(
            model_name='eventmodel',
            name='website',
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='EventActivities',
            field=tinymce.models.HTMLField(default='', help_text='Event activities with rich text editor'),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='EventActivitiesimageOne',
            field=models.ImageField(blank=True, help_text='Event activities image 1', null=True, upload_to='events/activities/'),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='EventActivitiesimageTwo',
            field=models.ImageField(blank=True, help_text='Event activities image 2', null=True, upload_to='events/activities/'),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='EventDetailimageOne',
            field=models.ImageField(blank=True, help_text='Event detail image 1', null=True, upload_to='events/details/'),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='EventDetailimageTwo',
            field=models.ImageField(blank=True, help_text='Event detail image 2', null=True, upload_to='events/details/'),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='EventDetails',
            field=tinymce.models.HTMLField(default='', help_text='Event details with rich text editor'),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='EventEntryPrice',
            field=models.CharField(default='$0', help_text="Event entry price (e.g., '$60')", max_length=50),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='EventParticipantButton',
            field=models.BooleanField(default=False, help_text='When clicked, marks that member is willing to participate'),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='EventVenue',
            field=models.CharField(default='TBD', help_text='Event venue', max_length=255),
        ),
    ]
