# Generated by Django 5.0.7 on 2025-08-02 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0012_alter_eventmodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmodel',
            name='EventParticipantButton',
        ),
        migrations.RemoveField(
            model_name='eventmodel',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='eventmodel',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='eventmodel',
            name='slug',
        ),
    ]
