# Generated by Django 5.0.7 on 2025-02-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0012_coursemodel_courseimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactEnquiryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactEnquiryDate', models.DateTimeField(auto_now_add=True)),
                ('contactEnquiryFirstName', models.CharField(max_length=255)),
                ('contactEnquiryLastName', models.CharField(max_length=255)),
                ('contactEnquiryPhoneNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('contactEnquiryEmail', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('contactEnquiryMessage', models.TextField()),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
