# Generated by Django 5.0.7 on 2025-02-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0013_contactenquirymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactenquirymodel',
            name='contactEnquiryDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
