# Generated by Django 5.0.7 on 2025-08-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0013_remove_eventmodel_eventparticipantbutton_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='EventImage',
            field=models.ImageField(blank=True, help_text='Main event image', null=True, upload_to='events/main/'),
        ),
    ]
