# Generated by Django 5.0.7 on 2025-02-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0014_alter_contactenquirymodel_contactenquirydate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberEnquiryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberEnquiryDate', models.DateField(auto_now_add=True)),
                ('memberEnquiryFirstName', models.CharField(max_length=255)),
                ('memberEnquiryLastName', models.CharField(max_length=255)),
                ('memberEnquiryPhoneNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('memberEnquiryEmail', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('memberEnquiryAddressLine1', models.CharField(max_length=255)),
                ('memberEnquiryAddressLine2', models.CharField(blank=True, max_length=255, null=True)),
                ('memberEnquiryTown', models.CharField(max_length=100)),
                ('memberEnquiryPostcode', models.CharField(max_length=20)),
                ('memberEnquiryCounty_or_city', models.CharField(max_length=100)),
                ('memberEnquiryDateOfBirth', models.DateField(blank=True, null=True)),
                ('memberEnquiryCompanyName', models.CharField(blank=True, max_length=255, null=True)),
                ('memberEnquiryHowDidYouHearAboutOGC', models.CharField(blank=True, max_length=255, null=True)),
                ('memberEnquiryNameOfMGCMember', models.CharField(blank=True, max_length=255, null=True)),
                ('memberEnquiryCurrentClub', models.CharField(blank=True, max_length=255, null=True)),
                ('memberEnquiryHandicap', models.CharField(blank=True, max_length=10, null=True)),
                ('memberEnquirySocietyDays', models.BooleanField(default=False)),
                ('memberEnquiryGroupCoaching', models.BooleanField(default=False)),
                ('memberEnquiryUkGolfTrips', models.BooleanField(default=False)),
                ('memberEnquiryGolfAbroad', models.BooleanField(default=False)),
                ('memberEnquiryMessage', models.TextField()),
                ('passportPhoto', models.ImageField(blank=True, null=True, upload_to='member_photos/')),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
