# Generated by Django 5.0.7 on 2025-08-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0014_alter_eventmodel_eventimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='EventDate',
            field=models.DateField(help_text='Event date'),
        ),
    ]
