# Generated by Django 5.0.7 on 2025-02-07 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0015_memberenquirymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberenquirymodel',
            name='memberEnquiryPlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberEnquiryPlan', to='apis.planmodel'),
        ),
    ]
