# Generated by Django 5.0.7 on 2025-08-02 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0015_alter_eventmodel_eventdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventInterestModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_interested', models.BooleanField(default=True)),
                ('interested_date', models.DateTimeField(auto_now_add=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_interests', to='apis.eventmodel')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_interests', to='apis.membermodel')),
            ],
            options={
                'verbose_name': 'Event Interest',
                'verbose_name_plural': 'Event Interests',
                'ordering': ['-interested_date'],
                'unique_together': {('member', 'event')},
            },
        ),
    ]
