# Generated by Django 5.0.7 on 2025-08-02 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0016_eventinterestmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmodel',
            name='EventDetailimageOne',
        ),
        migrations.RemoveField(
            model_name='eventmodel',
            name='EventDetailimageTwo',
        ),
    ]
