# Generated by Django 5.0.7 on 2025-02-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0016_memberenquirymodel_memberenquiryplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberenquirymodel',
            name='memberEnquiryEmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
