# Generated by Django 5.0.7 on 2025-08-02 11:58

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0017_remove_event_detail_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('instructorName', models.CharField(help_text='Instructor name', max_length=255)),
                ('instructorPosition', models.CharField(help_text='Instructor position/role', max_length=255)),
                ('instructorPhoto', models.ImageField(blank=True, help_text='Instructor photo', null=True, upload_to='instructor_photos/')),
                ('instructorBio', models.TextField(blank=True, help_text='Instructor biography', null=True)),
                ('facebookUrl', models.URLField(blank=True, help_text='Facebook profile URL', max_length=500, null=True)),
                ('instagramUrl', models.URLField(blank=True, help_text='Instagram profile URL', max_length=500, null=True)),
                ('twitterUrl', models.URLField(blank=True, help_text='X (Twitter) profile URL', max_length=500, null=True)),
                ('linkedinUrl', models.URLField(blank=True, help_text='LinkedIn profile URL', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is instructor active/visible')),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instructor',
                'verbose_name_plural': 'Instructors',
                'ordering': ['instructorName'],
            },
        ),
        migrations.CreateModel(
            name='ProtocolModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('protocolTitle', models.CharField(help_text='Protocol title', max_length=255)),
                ('protocolDescription', tinymce.models.HTMLField(help_text='Protocol description with rich text editor')),
                ('is_active', models.BooleanField(default=True, help_text='Is protocol active/visible')),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Protocol',
                'verbose_name_plural': 'Protocols',
                'ordering': ['-createdAt'],
            },
        ),
    ]
