# Generated by Django 5.0.7 on 2025-02-11 04:58

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0017_alter_memberenquirymodel_memberenquiryemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='blogHighlight',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='golfHighlight',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='blogDescription',
            field=tinymce.models.HTMLField(),
        ),
    ]
