# Generated by Django 5.0.7 on 2025-08-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0018_instructormodel_protocolmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructormodel',
            name='facebookUrl',
        ),
        migrations.RemoveField(
            model_name='instructormodel',
            name='instagramUrl',
        ),
        migrations.RemoveField(
            model_name='instructormodel',
            name='instructorBio',
        ),
        migrations.RemoveField(
            model_name='instructormodel',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='instructormodel',
            name='linkedinUrl',
        ),
        migrations.RemoveField(
            model_name='instructormodel',
            name='twitterUrl',
        ),
        migrations.RemoveField(
            model_name='protocolmodel',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='protocolmodel',
            name='protocolDescription',
            field=models.TextField(help_text='Protocol description'),
        ),
    ]
