# Generated by Django 5.0.7 on 2025-02-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0018_blogmodel_bloghighlight_coursemodel_golfhighlight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conceptHighlight', models.CharField(max_length=200)),
                ('conceptHeadingOne', models.CharField(max_length=255)),
                ('conceptParaOne', models.CharField(max_length=1000)),
                ('conceptHeadingTwo', models.CharField(max_length=255)),
                ('conceptParaTwo', models.CharField(max_length=1000)),
                ('conceptHeadingThree', models.CharField(max_length=255)),
                ('conceptParaThree', models.CharField(max_length=1000)),
                ('conceptHeadingFour', models.CharField(max_length=255)),
                ('conceptParaFour', models.CharField(max_length=1000)),
                ('conceptHeadingFive', models.CharField(max_length=255)),
                ('conceptParaFive', models.CharField(max_length=1000)),
                ('conceptHeadingSix', models.CharField(max_length=255)),
                ('conceptParaSix', models.CharField(max_length=1000)),
                ('conceptHeadingSeven', models.CharField(max_length=255)),
                ('conceptParaSeven', models.CharField(max_length=1000)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
