# Generated by Django 5.0.7 on 2025-02-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0019_conceptmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptmodel',
            name='conceptHighlight',
            field=models.CharField(max_length=255),
        ),
    ]
