# Generated by Django 5.0.7 on 2025-08-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0019_remove_instructormodel_facebookurl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructormodel',
            name='facebookUrl',
            field=models.URLField(blank=True, help_text='Facebook profile URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='instructormodel',
            name='instagramUrl',
            field=models.URLField(blank=True, help_text='Instagram profile URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='instructormodel',
            name='twitterUrl',
            field=models.URLField(blank=True, help_text='Twitter/X profile URL', max_length=500, null=True),
        ),
    ]
