# Generated by Django 5.0.7 on 2025-08-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0020_add_social_media_to_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the message sender', max_length=255)),
                ('email', models.EmailField(help_text='Email address of the sender', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Phone number of the sender', max_length=20, null=True)),
                ('subject', models.CharField(help_text='Message subject', max_length=255)),
                ('description', models.TextField(help_text='Message description/content')),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('closed', 'Closed')], default='new', help_text='Message status', max_length=20)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-createdAt'],
            },
        ),
    ]
