# Generated by Django 5.0.7 on 2025-08-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0021_messagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('faqQuestion', models.CharField(help_text='FAQ question', max_length=500)),
                ('faqAnswer', models.TextField(help_text='FAQ answer')),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['-createdAt'],
            },
        ),
    ]
