# Generated by Django 5.0.7 on 2025-08-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0022_add_faq_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='courseOpenFrom',
            field=models.TimeField(blank=True, help_text='Course opening time (e.g., 06:00)', null=True),
        ),
    ]
