# Generated by Django 5.0.12 on 2025-08-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0023_alter_course_open_from_to_timefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenitiesmodel',
            name='amenitiesDescription',
            field=models.TextField(blank=True, help_text='Detailed description of the amenity', null=True),
        ),
    ]
