# Generated by Django 5.0.7 on 2025-08-05 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0024_remove_price_per_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='is_join_request',
            field=models.BooleanField(default=False, help_text='Whether this booking is a join request'),
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='original_booking',
            field=models.ForeignKey(blank=True, help_text='Original booking this join request is for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='apis.bookingmodel'),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('join_request', 'Join Request'), ('join_approved', 'Join Approved'), ('join_rejected', 'Join Rejected'), ('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='apis.membermodel')),
                ('related_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='apis.bookingmodel')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to='apis.membermodel')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-createdAt'],
            },
        ),
    ]
