# Generated by Django 5.0.7 on 2025-08-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0025_bookingmodel_is_join_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='booking_id',
            field=models.CharField(blank=True, help_text='Unique booking ID in format MGC25AUG05', max_length=20, null=True, unique=True),
        ),
    ]
