# Generated by Django 5.0.7 on 2025-08-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0026_bookingmodel_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planmodel',
            name='planCycle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='planmodel',
            name='planDuration',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='planmodel',
            name='planType',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterModelOptions(
            name='planmodel',
            options={'verbose_name': 'Plan', 'verbose_name_plural': 'Plans'},
        ),
        migrations.AlterField(
            model_name='memberenquirymodel',
            name='memberEnquiryPlan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='plan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PlanCycleModel',
        ),
        migrations.DeleteModel(
            name='PlanDurationModel',
        ),
        migrations.DeleteModel(
            name='PlanTypeModel',
        ),
    ]
