# Generated by Django 5.0.7 on 2025-08-05 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0027_update_plan_model_simplified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planmodel',
            name='planCycle',
        ),
        migrations.RemoveField(
            model_name='planmodel',
            name='planType',
        ),
    ]
