# Generated by Django 5.0.7 on 2025-08-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0028_remove_plan_type_and_cycle_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planmodel',
            name='planDuration',
            field=models.IntegerField(blank=True, help_text='Duration in years', null=True),
        ),
    ]
