# Generated by Django 5.0.12 on 2025-08-05 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0029_update_plan_duration_to_years'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanFeatureModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('featureName', models.CharField(help_text='Feature name', max_length=255)),
                ('isIncluded', models.BooleanField(default=True, help_text='Whether this feature is included in the plan')),
                ('order', models.IntegerField(default=0, help_text='Display order of the feature')),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='apis.planmodel')),
            ],
            options={
                'verbose_name': 'Plan Feature',
                'verbose_name_plural': 'Plan Features',
                'ordering': ['order', 'featureName'],
            },
        ),
    ]
