# Generated by Django 5.0.7 on 2025-08-18 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0031_remove_payment_fields_add_alternate_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When the join request was approved', null=True),
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Member who approved this join request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bookings', to='apis.membermodel'),
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='is_multi_slot_booking',
            field=models.BooleanField(default=False, help_text='Whether this is part of a multi-slot booking'),
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='multi_slot_group_id',
            field=models.CharField(blank=True, help_text='Group ID for multi-slot bookings', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='slot_order',
            field=models.PositiveIntegerField(default=1, help_text='Order of slot in multi-slot booking'),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
