# Generated by Django 5.0.7 on 2025-08-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0032_bookingmodel_approved_at_bookingmodel_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='multi_slot_booking_id',
            field=models.CharField(blank=True, help_text='Single booking ID for multi-slot bookings', max_length=50, null=True),
        ),
    ]
