# Generated by Django 5.0.7 on 2025-08-21 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0033_bookingmodel_multi_slot_booking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingmodel',
            name='is_multi_slot_booking',
        ),
        migrations.RemoveField(
            model_name='bookingmodel',
            name='multi_slot_booking_id',
        ),
        migrations.RemoveField(
            model_name='bookingmodel',
            name='multi_slot_group_id',
        ),
        migrations.RemoveField(
            model_name='bookingmodel',
            name='slot_order',
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='has_multiple_slots',
            field=models.BooleanField(default=False, help_text='Whether this booking has multiple slots'),
        ),
        migrations.CreateModel(
            name='BookingSlotModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_time', models.TimeField(help_text='Time for this specific slot')),
                ('participants', models.PositiveIntegerField(default=1, help_text='Number of participants for this slot')),
                ('slot_order', models.PositiveIntegerField(default=1, help_text='Order of this slot in the booking')),
                ('slot_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('slot_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='confirmed', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='apis.bookingmodel')),
                ('tee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_slots', to='apis.teemodel')),
            ],
            options={
                'verbose_name': 'Booking Slot',
                'verbose_name_plural': 'Booking Slots',
                'ordering': ['slot_order'],
            },
        ),
    ]
