# Generated by Django 5.0.7 on 2025-08-21 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0034_remove_bookingmodel_is_multi_slot_booking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingmodel',
            name='totalPrice',
        ),
        migrations.RemoveField(
            model_name='bookingslotmodel',
            name='slot_price',
        ),
    ]
