# Generated by Django 5.0.7 on 2025-08-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0036_enhance_booking_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingslotmodel',
            name='courseName',
        ),
        migrations.RemoveField(
            model_name='bookingslotmodel',
            name='teeName',
        ),
        migrations.AddField(
            model_name='bookingslotmodel',
            name='slot_date',
            field=models.DateField(blank=True, help_text='Date for this specific slot', null=True),
        ),
    ]
