# Generated by Django 5.0.7 on 2025-08-22 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0038_populate_slot_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingmodel',
            name='bookingDate',
        ),
        migrations.RemoveField(
            model_name='bookingmodel',
            name='has_multiple_slots',
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='booking_time',
            field=models.TimeField(blank=True, help_text='Time for this specific slot', null=True),
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='group_id',
            field=models.CharField(blank=True, help_text='Group ID for multi-slot bookings', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='slot_date',
            field=models.DateField(blank=True, help_text='Date for this specific slot', null=True),
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='tee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='apis.teemodel'),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='booking_id',
            field=models.CharField(blank=True, help_text='Unique booking ID in format MGCBK25AUG00010', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='participants',
            field=models.PositiveIntegerField(default=1, help_text='Number of participants for this slot'),
        ),
        migrations.DeleteModel(
            name='BookingSlotModel',
        ),
    ]
