# Generated by Django 5.0.7 on 2025-08-26 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0039_remove_bookingmodel_bookingdate_and_more'),
    ]

    operations = [
    ]
