# Generated by Django 5.0.7 on 2025-08-26 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0040_merge_20250826_1347'),
        ('apis', 'add_request_id_field'),
    ]

    operations = [
    ]
