# Generated by Django 5.0.7 on 2025-08-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0041_merge_0040_merge_20250826_1347_add_request_id_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingmodel',
            options={'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.RenameIndex(
            model_name='bookingmodel',
            new_name='apis_bookin_request_24ea86_idx',
            old_name='apis_bookin_request_123456_idx',
        ),
        migrations.AddIndex(
            model_name='bookingmodel',
            index=models.Index(fields=['booking_id'], name='apis_bookin_booking_cf9982_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingmodel',
            index=models.Index(fields=['slot_date', 'booking_time', 'tee'], name='apis_bookin_slot_da_7ab447_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingmodel',
            index=models.Index(fields=['member', 'status'], name='apis_bookin_member__46e259_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingmodel',
            index=models.Index(fields=['createdAt'], name='apis_bookin_created_c9b3b3_idx'),
        ),
        migrations.AlterModelTable(
            name='bookingmodel',
            table='apis_bookingmodel',
        ),
    ]
