# Generated by Django 5.0.7 on 2025-08-26 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0042_alter_bookingmodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinRequestModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_id', models.CharField(blank=True, help_text='Unique request ID in format MGCRQ25AUG00010', max_length=20, null=True, unique=True)),
                ('participants', models.PositiveIntegerField(default=1, help_text='Number of participants requesting to join')),
                ('status', models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_approval', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, help_text='When the join request was approved', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Join Request',
                'verbose_name_plural': 'Join Requests',
                'db_table': 'apis_joinrequestmodel',
            },
        ),
        migrations.RemoveIndex(
            model_name='bookingmodel',
            name='apis_bookin_request_24ea86_idx',
        ),
        migrations.RemoveField(
            model_name='bookingmodel',
            name='request_id',
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='DEPRECATED: When the join request was approved', null=True),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Member who approved this join request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_approved_bookings', to='apis.membermodel'),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='is_join_request',
            field=models.BooleanField(default=False, help_text='DEPRECATED: Whether this booking is a join request'),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='original_booking',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Original booking this join request is for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_join_requests', to='apis.bookingmodel'),
        ),
        migrations.AddField(
            model_name='joinrequestmodel',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Member who approved this join request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_join_requests', to='apis.membermodel'),
        ),
        migrations.AddField(
            model_name='joinrequestmodel',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='apis.membermodel'),
        ),
        migrations.AddField(
            model_name='joinrequestmodel',
            name='original_booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='apis.bookingmodel'),
        ),
        migrations.AddIndex(
            model_name='joinrequestmodel',
            index=models.Index(fields=['request_id'], name='apis_joinre_request_3514b2_idx'),
        ),
        migrations.AddIndex(
            model_name='joinrequestmodel',
            index=models.Index(fields=['original_booking', 'status'], name='apis_joinre_origina_183725_idx'),
        ),
        migrations.AddIndex(
            model_name='joinrequestmodel',
            index=models.Index(fields=['member', 'status'], name='apis_joinre_member__a13ed6_idx'),
        ),
        migrations.AddIndex(
            model_name='joinrequestmodel',
            index=models.Index(fields=['createdAt'], name='apis_joinre_created_22859d_idx'),
        ),
    ]
