# Generated by Django 5.0.7 on 2025-08-26 17:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0043_joinrequestmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinrequestmodel',
            name='request_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the join request was made'),
        ),
        migrations.AddField(
            model_name='joinrequestmodel',
            name='requester_member_id',
            field=models.CharField(blank=True, help_text='Golf Club ID of the requester', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationmodel',
            name='notification_type',
            field=models.CharField(choices=[('join_request', 'Join Request'), ('join_approved', 'Join Approved'), ('join_rejected', 'Join Rejected'), ('booking_confirmed', 'Booking Confirmed')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='joinrequestmodel',
            index=models.Index(fields=['status', 'hideStatus'], name='apis_joinre_status_af6ea9_idx'),
        ),
    ]
