# Generated by Django 5.0.7 on 2025-08-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0044_joinrequestmodel_request_date_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='joinrequestmodel',
            name='apis_joinre_status_af6ea9_idx',
        ),
        migrations.RemoveField(
            model_name='joinrequestmodel',
            name='request_date',
        ),
        migrations.RemoveField(
            model_name='joinrequestmodel',
            name='requester_member_id',
        ),
        migrations.AlterField(
            model_name='notificationmodel',
            name='notification_type',
            field=models.CharField(choices=[('join_request_received', 'Join Request Received'), ('join_request_approved', 'Join Request Approved'), ('join_request_rejected', 'Join Request Rejected'), ('join_request', 'Join Request'), ('join_approved', 'Join Approved'), ('join_rejected', 'Join Rejected'), ('booking_confirmed', 'Booking Confirmed')], max_length=25),
        ),
    ]
