# Generated by Django 5.0.12 on 2026-07-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0045_remove_joinrequestmodel_apis_joinre_status_af6ea9_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='joinRequestExpiryHours',
            field=models.PositiveIntegerField(blank=True, help_text='Hours before tee time when pending join requests auto-expire. Leave blank to disable auto-expiry for this course.', null=True),
        ),
        migrations.AlterField(
            model_name='joinrequestmodel',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending_approval', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationmodel',
            name='notification_type',
            field=models.CharField(choices=[('join_request_received', 'Join Request Received'), ('join_request_approved', 'Join Request Approved'), ('join_request_rejected', 'Join Request Rejected'), ('join_request_expired', 'Join Request Expired'), ('join_request', 'Join Request'), ('join_approved', 'Join Approved'), ('join_rejected', 'Join Rejected'), ('booking_confirmed', 'Booking Confirmed')], max_length=25),
        ),
    ]
