# Generated by Django 5.0.7 on 2026-07-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0046_coursemodel_joinrequestexpiryhours_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bookingmodel',
            constraint=models.UniqueConstraint(condition=models.Q(('hideStatus', 0), ('is_join_request', False), ('status__in', ['pending', 'confirmed', 'completed', 'approved'])), fields=('member', 'slot_date', 'booking_time'), name='unique_member_slot_datetime'),
        ),
    ]
