# Generated by Django 5.0.7 on 2026-07-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0047_bookingmodel_unique_member_slot_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membermodel',
            name='golfClubId',
            field=models.CharField(blank=True, help_text='Assigned on save in the format MGC25100001; never set by the client', max_length=100, null=True, unique=True),
        ),
    ]
