# Generated by Django 5.0.12 on 2026-08-06 05:32

import apis.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0049_security_password_hardening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='blogImage',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/', validators=[apis.validators.ValidatedUpload(allowed=['jpg', 'jpeg', 'png', 'gif', 'webp'], kind='image')]),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='courseImage',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/', validators=[apis.validators.ValidatedUpload(allowed=['jpg', 'jpeg', 'png', 'gif', 'webp'], kind='image')]),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='EventActivitiesimageOne',
            field=models.ImageField(blank=True, help_text='Event activities image 1', null=True, upload_to='events/activities/', validators=[apis.validators.ValidatedUpload(allowed=['jpg', 'jpeg', 'png', 'gif', 'webp'], kind='image')]),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='EventActivitiesimageTwo',
            field=models.ImageField(blank=True, help_text='Event activities image 2', null=True, upload_to='events/activities/', validators=[apis.validators.ValidatedUpload(allowed=['jpg', 'jpeg', 'png', 'gif', 'webp'], kind='image')]),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='EventImage',
            field=models.ImageField(blank=True, help_text='Main event image', null=True, upload_to='events/main/', validators=[apis.validators.ValidatedUpload(allowed=['jpg', 'jpeg', 'png', 'gif', 'webp'], kind='image')]),
        ),
        migrations.AlterField(
            model_name='instructormodel',
            name='instructorPhoto',
            field=models.ImageField(blank=True, help_text='Instructor photo', null=True, upload_to='instructor_photos/', validators=[apis.validators.ValidatedUpload(allowed=['jpg', 'jpeg', 'png', 'gif', 'webp'], kind='image')]),
        ),
    ]
