# Generated by Django 4.2.7 on 2025-01-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),  # Update this to the latest migration
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='request_id',
            field=models.CharField(blank=True, help_text='Unique request ID in format MGCRQ25AUG00010 for join requests', max_length=20, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='bookingmodel',
            index=models.Index(fields=['request_id'], name='apis_bookin_request_123456_idx'),
        ),
    ]
